<?php
//ﾃﾞｰﾀﾍﾞｰｽ基本情報,configに記載
define('DB_HOST','mysql:dbname=test;host=localhost');
define('DB_USER','root');
define('DB_PASS','');
define('DB_NAME','test');
define('ERROR_NAME','お名前をご記入ください。');
define('ERROR_MAIL','ｱﾄﾞﾚｽをご記入ください');
define('ERROR_PASS','ﾊﾟｽﾜｰﾄﾞをご記入ください。');
define('ERROR_MSG','ﾊﾟｽﾜｰﾄﾞは6文字以上です');
define('ERROR_MSG1','ﾊﾟｽﾜｰﾄﾞは32文字以下となります。');
define('ERROR_MSG2','ｱﾄﾞﾚｽを半角英数字でご登録ください');
define('ERROR_MSG3','ﾊﾟｽﾜｰﾄﾞは半角英数字でご登録ください');
define('ERROR_MSG4','既にこのｱﾄﾞﾚｽは登録されております');
define('ERROR_MSG5','不正なｱｸｾｽになります');
define('ERROR_MAG6','ｱﾄﾞﾚｽをご確認くださいませ');
define('SUCCESS_MSG','ﾃﾞｰﾀﾍﾞｰｽ登録が完了いたしました。');
